---
title: "Welcome To L2C Blog"
date: 2018-09-09
---
title: Learn 2 Code
author: Bhakti Budiman Novanda 
email: myforework@live.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, it is always a good idea to learn programming language. In this section I will
try to guide you so that you gain a good insight about programming world. Enjoy!

# social links
twitter_username: your-twitter-handle
github_username:  bhaktitud

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
